import type { NextPage } from 'next'
import Head from 'next/head'
import { useRouter } from 'next/router'
import { Flex, Box, Text, Button, Stack, Center } from '@chakra-ui/react'

const Home: NextPage = () => {
  const router = useRouter();

  const handleDoubleClick = () => {
    router.push('/chess')
  }

  return (
    <>
      <Head>
        <title>Chess Game</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Flex h='100vh' direction={{ base: 'column', sm: 'column', md: 'row', lg: 'row' }}>
        <Box flex='2' bg='#f2f2f2' bgImage='/img/home_bg.png' bgSize='80%' bgPosition='center center' bgRepeat='no-repeat'>
        </Box>
        <Box flex='1'>
          <Flex w="100%" h='100%' direction='column' align='center' justify='center' gap={{ base: 4, sm: 4, md: 10, lg: 16 }}>
            <Stack direction={{ sm: 'row', md: 'column' }}>
                <Text color='blackAlpha.800' fontSize={{ base: '4xl', sm: '4xl', md: '6xl', lg: '7xl' }} fontWeight='bold' lineHeight='1.1'>欢乐</Text>
                <Text color='blackAlpha.800' fontSize={{ base: '4xl', sm: '4xl', md: '6xl', lg: '7xl' }} fontWeight='bold' lineHeight='1.1'>中国象棋</Text>
            </Stack>
            <Stack minW='80%' gap={4}>
              <Flex direction='column'>
                <Button colorScheme='teal' h={14} rounded='none' onClick={handleDoubleClick}>
                  开始游戏
                </Button>
              </Flex>
              <Flex direction='column' align='flex-end'>
                <Text color='blackAlpha.700' fontSize='xl' fontWeight='bold' lineHeight='1.1'>中国のチェス</Text>
                <Text color='blackAlpha.700' fontSize='xl' fontWeight='bold' lineHeight='1.1'>CHINESE CHESS</Text>
              </Flex>
            </Stack>
          </Flex>
        </Box>
      </Flex>
    </>
  )
}

export default Home
